module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Array
import Dict
import Expect
import Fuzz
import Gadget
import Gadget.Adapter.Diff
import Gadget.Adapter.Form
import Gadget.Adapter.Fuzz
import Gadget.Adapter.Html
import Gadget.Adapter.Json
import Gadget.Adapter.Random
import Gadget.Adapter.String
import Gadget.IR
import Html
import Html.Attributes
import Html.Events
import Json.Decode
import Json.Encode
import Parser
import Platform.Cmd
import Platform.Sub
import Random
import Set
import Test


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Json.Encode.Value
                            unused =
                                json__Readme_0
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        decoded__Readme_0
                            |> Expect.equal
                                (Result.Ok { name = "Ed", age = 44 })
                    )
                , Test.test
                    "2"
                    (\() ->
                        fuzzed__Readme_0
                            |> Expect.equal [ { age = 92, name = "o \n\\" } ]
                    )
                ]
            ]
        , Test.describe
            "Gadget"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Person__Gadget__Header_0
                                unused =
                                    personGadget__Gadget__Header_0
                            in
                            Expect.pass
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Shape__Gadget__Header_1
                                unused =
                                    shapeGadget__Gadget__Header_1
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "array"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Array.Array Basics.Int)
                                unused =
                                    arrayGadget__Gadget__array_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "dict"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Dict.Dict Basics.Int String.String)
                                unused =
                                    dictGadget__Gadget__dict_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "filterMap"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused :
                                    Gadget.Gadget a
                                    -> Gadget.Gadget ( a, List a )
                                unused =
                                    nonEmptyListGadget__Gadget__filterMap_0
                            in
                            Expect.pass
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused :
                                    Gadget.Gadget a
                                    -> Gadget.Gadget ( a, List a )
                                unused =
                                    nonEmptyListGadget__Gadget__filterMap_1
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "lazy"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget Tree__Gadget__lazy_0
                                unused =
                                    treeGadget__Gadget__lazy_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "list"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (List Basics.Int)
                                unused =
                                    listGadget__Gadget__list_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "map"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (List Char.Char)
                                unused =
                                    charListGadget__Gadget__map_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "maybe"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Maybe.Maybe Basics.Int)
                                unused =
                                    maybeGadget__Gadget__maybe_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "result"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Result.Result String.String Basics.Int)
                                unused =
                                    resultGadget__Gadget__result_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "set"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget (Set.Set Basics.Int)
                                unused =
                                    dictGadget__Gadget__set_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "triple"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget ( String.String, Basics.Int, Basics.Float )
                                unused =
                                    tripleGadget__Gadget__triple_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "tuple"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Gadget ( String.String, Basics.Int )
                                unused =
                                    tupleGadget__Gadget__tuple_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Diff"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Adapter.Diff.Changes
                                unused =
                                    changes__Gadget_Adapter_Diff__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Gadget.Adapter.Diff.patch
                                gadget__Gadget_Adapter_Diff__Header_0
                                changes__Gadget_Adapter_Diff__Header_0
                                oldValue__Gadget_Adapter_Diff__Header_0
                                |> Expect.equal (Result.Ok [ 1, 2, 3, 4 ])
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Form"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : ( Model__Gadget_Adapter_Form__Header_0, Platform.Cmd.Cmd Msg__Gadget_Adapter_Form__Header_0 )
                                unused =
                                    init__Gadget_Adapter_Form__Header_0
                            in
                            Expect.pass
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.Adapter.Form.Control Basics.Int
                                unused =
                                    counter__Gadget_Adapter_Form__Header_1
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Fuzz"
            [ Test.describe
                "fuzzer"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            fuzzedPerson__Gadget_Adapter_Fuzz__fuzzer_0
                                |> Expect.equal
                                    [ { age = 92, name = "o \n\\" } ]
                        )
                    ]
                ]
            , Test.describe
                "fuzzerWithOverrides"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            fuzzedPerson__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0
                                |> Expect.equal [ { age = 105, name = "Ed" } ]
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Html"
            [ Test.describe
                "view"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Html.Html msg
                                unused =
                                    view__Gadget_Adapter_Html__view_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Json"
            [ Test.describe
                "decoder"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            result__Gadget_Adapter_Json__decoder_0
                                |> Expect.equal (Result.Ok 1)
                        )
                    ]
                ]
            , Test.describe
                "encode"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Json.Encode.Value
                                unused =
                                    json__Gadget_Adapter_Json__encode_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            jsonString__Gadget_Adapter_Json__encode_0
                                |> Expect.equal "1"
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.Random"
            [ Test.describe
                "generator"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            randomPerson__Gadget_Adapter_Random__generator_0
                                |> Expect.equal
                                    (Maybe.Just { age = -1353461051, name = "" })
                        )
                    ]
                ]
            , Test.describe
                "listLength"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            randomList__Gadget_Adapter_Random__listLength_0
                                |> Expect.equal
                                    (Maybe.Just
                                        [ Basics.True
                                        , Basics.False
                                        , Basics.False
                                        ]
                                    )
                        )
                    ]
                ]
            , Test.describe
                "range"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            randomInt__Gadget_Adapter_Random__range_0
                                |> Expect.equal (Maybe.Just 6)
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.Adapter.String"
            [ Test.describe
                "parser"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            parsed__Gadget_Adapter_String__parser_0
                                |> Expect.equal (Result.Ok [ 1, 2, 3 ])
                        )
                    ]
                ]
            , Test.describe
                "print"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            printed__Gadget_Adapter_String__print_0
                                |> Expect.equal "l[i(1),i(2),i(3)]"
                        )
                    ]
                ]
            ]
        , Test.describe
            "Gadget.IR"
            [ Test.describe
                "MetadataTools"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            irValue__Gadget_IR__MetadataTools_0
                                |> Expect.equal
                                    (Maybe.Just
                                        (Gadget.IR.TupleValue
                                            (Gadget.IR.IntValue 0)
                                            (Gadget.IR.IntValue 10)
                                        )
                                    )
                        )
                    , Test.test
                        "1"
                        (\() ->
                            elmValue__Gadget_IR__MetadataTools_0
                                |> Expect.equal (Maybe.Just ( 0, 10 ))
                        )
                    , Test.test
                        "2"
                        (\() ->
                            let
                                unused : List ( String.String, List ( String.String, Gadget.IR.Value ) )
                                unused =
                                    allValues__Gadget_IR__MetadataTools_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "makeMetadataTools"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Gadget.IR.MetadataTools meta a
                                unused =
                                    tools__Gadget_IR__makeMetadataTools_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        ]


type alias Person__Readme_0 =
    { name : String.String, age : Basics.Int }


input__Readme_0 =
    { name = "Ed", age = 44 }


gadget__Readme_0 : Gadget.Gadget Person__Readme_0
gadget__Readme_0 =
    Gadget.record Person__Readme_0
        |> Gadget.field "name" .name Gadget.string
        |> Gadget.field "age" .age Gadget.int
        |> Gadget.endRecord


json__Readme_0 =
    Gadget.Adapter.Json.encode gadget__Readme_0 input__Readme_0


decoded__Readme_0 =
    Json.Decode.decodeValue
        (Gadget.Adapter.Json.decoder gadget__Readme_0)
        json__Readme_0


fuzzed__Readme_0 =
    Fuzz.examples 1 (Gadget.Adapter.Fuzz.fuzzer gadget__Readme_0)


type alias Person__Gadget__Header_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget__Header_0 =
    Gadget.record Person__Gadget__Header_0
        |> Gadget.field "name" .name Gadget.string
        |> Gadget.field "age" .age Gadget.int
        |> Gadget.endRecord


type Shape__Gadget__Header_1
    = Rectangle__Gadget__Header_1 Basics.Int Basics.Int
    | Circle__Gadget__Header_1 Basics.Int


shapeGadget__Gadget__Header_1 =
    Gadget.custom
        (\rectangle circle variant ->
            case variant of
                Rectangle__Gadget__Header_1 width height ->
                    rectangle width height

                Circle__Gadget__Header_1 radius ->
                    circle radius
        )
        |> Gadget.variant2
            "Rectangle"
            Rectangle__Gadget__Header_1
            Gadget.int
            Gadget.int
        |> Gadget.variant1 "Circle" Circle__Gadget__Header_1 Gadget.int
        |> Gadget.endCustom


arrayGadget__Gadget__array_0 =
    Gadget.array Gadget.int


dictGadget__Gadget__dict_0 =
    Gadget.dict Gadget.int Gadget.string


nonEmptyListGadget__Gadget__filterMap_0 a =
    Gadget.list a
        |> Gadget.filterMap
            (\list ->
                case list of
                    [] ->
                        Result.Err [ "must contain at least one item" ]

                    h :: t ->
                        Result.Ok ( h, t )
            )
            (\( h, t ) -> h :: t)


nonEmptyListGadget__Gadget__filterMap_1 a =
    Gadget.tuple a (Gadget.list a)


type Tree__Gadget__lazy_0
    = Leaf__Gadget__lazy_0 String.String
    | Branch__Gadget__lazy_0 Tree__Gadget__lazy_0 Tree__Gadget__lazy_0


treeGadget__Gadget__lazy_0 =
    Gadget.custom
        (\leaf branch tree ->
            case tree of
                Leaf__Gadget__lazy_0 value ->
                    leaf value

                Branch__Gadget__lazy_0 branch0 branch1 ->
                    branch branch0 branch1
        )
        |> Gadget.variant1 "Leaf" Leaf__Gadget__lazy_0 Gadget.string
        |> Gadget.variant2
            "Branch"
            Branch__Gadget__lazy_0
            (Gadget.lazy (\() -> treeGadget__Gadget__lazy_0))
            (Gadget.lazy (\() -> treeGadget__Gadget__lazy_0))
        |> Gadget.endCustom


listGadget__Gadget__list_0 =
    Gadget.list Gadget.int


charListGadget__Gadget__map_0 =
    Gadget.string |> Gadget.map String.toList String.fromList


maybeGadget__Gadget__maybe_0 =
    Gadget.maybe Gadget.int


resultGadget__Gadget__result_0 =
    Gadget.result Gadget.string Gadget.int


dictGadget__Gadget__set_0 =
    Gadget.set Gadget.int


tripleGadget__Gadget__triple_0 =
    Gadget.triple Gadget.string Gadget.int Gadget.float


tupleGadget__Gadget__tuple_0 =
    Gadget.tuple Gadget.string Gadget.int


gadget__Gadget_Adapter_Diff__Header_0 =
    Gadget.list Gadget.int


oldValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3 ]


newValue__Gadget_Adapter_Diff__Header_0 =
    [ 1, 2, 3, 4 ]


changes__Gadget_Adapter_Diff__Header_0 =
    Gadget.Adapter.Diff.diff
        gadget__Gadget_Adapter_Diff__Header_0
        oldValue__Gadget_Adapter_Diff__Header_0
        newValue__Gadget_Adapter_Diff__Header_0


gadget__Gadget_Adapter_Form__Header_0 : Gadget.Gadget ( Basics.Bool, String.String )
gadget__Gadget_Adapter_Form__Header_0 =
    Gadget.tuple Gadget.bool Gadget.string


type Msg__Gadget_Adapter_Form__Header_0
    = FormChanged__Gadget_Adapter_Form__Header_0 Gadget.Adapter.Form.Msg
    | FormSubmitted__Gadget_Adapter_Form__Header_0


type alias Model__Gadget_Adapter_Form__Header_0 =
    { formState : Gadget.Adapter.Form.Model, otherFields : () }


form__Gadget_Adapter_Form__Header_0 : Gadget.Adapter.Form.Form Msg__Gadget_Adapter_Form__Header_0 ( Basics.Bool, String.String )
form__Gadget_Adapter_Form__Header_0 =
    Gadget.Adapter.Form.fromGadget
        FormChanged__Gadget_Adapter_Form__Header_0
        gadget__Gadget_Adapter_Form__Header_0


init__Gadget_Adapter_Form__Header_0 =
    let
        ( formState, formCmd ) =
            form__Gadget_Adapter_Form__Header_0.init
    in
    ( { formState = formState, otherFields = () }, formCmd )


update__Gadget_Adapter_Form__Header_0 msg model =
    case msg of
        FormChanged__Gadget_Adapter_Form__Header_0 formMsg ->
            let
                ( formState, formCmd ) =
                    form__Gadget_Adapter_Form__Header_0.update
                        formMsg
                        model.formState
            in
            ( { model | formState = formState }, formCmd )

        FormSubmitted__Gadget_Adapter_Form__Header_0 ->
            let
                result =
                    form__Gadget_Adapter_Form__Header_0.submit model.formState
            in
            case result of
                Result.Ok output ->
                    let
                        _ =
                            Debug.log "Success!" output
                    in
                    ( model, Platform.Cmd.none )

                Result.Err errors ->
                    let
                        _ =
                            Debug.log "Failure!" errors
                    in
                    ( model, Platform.Cmd.none )


view__Gadget_Adapter_Form__Header_0 model =
    form__Gadget_Adapter_Form__Header_0.view model.formState


subscriptions__Gadget_Adapter_Form__Header_0 model =
    form__Gadget_Adapter_Form__Header_0.subscriptions model.formState


counter__Gadget_Adapter_Form__Header_1 =
    Gadget.Adapter.Form.makeControl
        { model = Gadget.int
        , msg = Gadget.bool
        , output = Gadget.int
        , init = ( 0, Platform.Cmd.none )
        , load = \output -> output
        , placeholder = 0
        , update =
            \msg model ->
                ( if msg then
                    model + 1

                  else
                    model - 1
                , Platform.Cmd.none
                )
        , view =
            \id model ->
                Html.div
                    [ Html.Attributes.id id ]
                    [ Html.button
                        [ Html.Events.onClick Basics.False ]
                        [ Html.text "-" ]
                    , Html.text (String.fromInt model)
                    , Html.button
                        [ Html.Events.onClick Basics.True ]
                        [ Html.text "+" ]
                    ]
        , subscriptions = \_ -> Platform.Sub.none
        , submit = \model -> Result.Ok model
        }


form__Gadget_Adapter_Form__Header_1 =
    let
        config =
            Gadget.Adapter.Form.defaultConfig
    in
    Gadget.Adapter.Form.fromGadgetWithConfig
        { config | int = counter__Gadget_Adapter_Form__Header_1 }
        Basics.identity
        Gadget.int


type alias Person__Gadget_Adapter_Fuzz__fuzzer_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Fuzz__fuzzer_0 =
    Gadget.record Person__Gadget_Adapter_Fuzz__fuzzer_0
        |> Gadget.field "name" .name Gadget.string
        |> Gadget.field "age" .age Gadget.int
        |> Gadget.endRecord


personFuzzer__Gadget_Adapter_Fuzz__fuzzer_0 =
    Gadget.Adapter.Fuzz.fuzzer personGadget__Gadget_Adapter_Fuzz__fuzzer_0


fuzzedPerson__Gadget_Adapter_Fuzz__fuzzer_0 =
    Fuzz.examples 1 personFuzzer__Gadget_Adapter_Fuzz__fuzzer_0


type alias Person__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Gadget.record Person__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0
        |> Gadget.field
            "name"
            .name
            nameGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0
        |> Gadget.field "age" .age Gadget.int
        |> Gadget.endRecord


nameGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Gadget.string |> Gadget.Adapter.Fuzz.useOverride "name"


personFuzzer__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Gadget.Adapter.Fuzz.fuzzerWithOverrides
        [ Gadget.Adapter.Fuzz.override "name" Gadget.string (Fuzz.constant "Ed")
        ]
        personGadget__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0


fuzzedPerson__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0 =
    Fuzz.examples 1 personFuzzer__Gadget_Adapter_Fuzz__fuzzerWithOverrides_0


gadget__Gadget_Adapter_Html__view_0 =
    Gadget.int


view__Gadget_Adapter_Html__view_0 =
    Gadget.Adapter.Html.view gadget__Gadget_Adapter_Html__view_0 1


gadget__Gadget_Adapter_Json__decoder_0 =
    Gadget.int


jsonString__Gadget_Adapter_Json__decoder_0 =
    "1"


decoder__Gadget_Adapter_Json__decoder_0 =
    Gadget.Adapter.Json.decoder gadget__Gadget_Adapter_Json__decoder_0


result__Gadget_Adapter_Json__decoder_0 =
    Json.Decode.decodeString
        decoder__Gadget_Adapter_Json__decoder_0
        jsonString__Gadget_Adapter_Json__decoder_0


gadget__Gadget_Adapter_Json__encode_0 =
    Gadget.int


json__Gadget_Adapter_Json__encode_0 =
    Gadget.Adapter.Json.encode gadget__Gadget_Adapter_Json__encode_0 1


jsonString__Gadget_Adapter_Json__encode_0 =
    Json.Encode.encode 0 json__Gadget_Adapter_Json__encode_0


type alias Person__Gadget_Adapter_Random__generator_0 =
    { name : String.String, age : Basics.Int }


personGadget__Gadget_Adapter_Random__generator_0 =
    Gadget.record Person__Gadget_Adapter_Random__generator_0
        |> Gadget.field "name" .name Gadget.string
        |> Gadget.field "age" .age Gadget.int
        |> Gadget.endRecord


personGenerator__Gadget_Adapter_Random__generator_0 =
    Gadget.Adapter.Random.generator
        personGadget__Gadget_Adapter_Random__generator_0


randomPerson__Gadget_Adapter_Random__generator_0 =
    Random.step
        personGenerator__Gadget_Adapter_Random__generator_0
        (Random.initialSeed 2)
        |> Tuple.first


listGadget__Gadget_Adapter_Random__listLength_0 =
    Gadget.list Gadget.bool |> Gadget.Adapter.Random.listLength 2 4


listGenerator__Gadget_Adapter_Random__listLength_0 =
    Gadget.Adapter.Random.generator
        listGadget__Gadget_Adapter_Random__listLength_0


randomList__Gadget_Adapter_Random__listLength_0 =
    Random.step
        listGenerator__Gadget_Adapter_Random__listLength_0
        (Random.initialSeed 0)
        |> Tuple.first


intGadget__Gadget_Adapter_Random__range_0 =
    Gadget.int |> Gadget.Adapter.Random.range 5 10


intGenerator__Gadget_Adapter_Random__range_0 =
    Gadget.Adapter.Random.generator intGadget__Gadget_Adapter_Random__range_0


randomInt__Gadget_Adapter_Random__range_0 =
    Random.step
        intGenerator__Gadget_Adapter_Random__range_0
        (Random.initialSeed 0)
        |> Tuple.first


parser__Gadget_Adapter_String__parser_0 =
    Gadget.Adapter.String.parser (Gadget.list Gadget.int)


parsed__Gadget_Adapter_String__parser_0 =
    Parser.run parser__Gadget_Adapter_String__parser_0 "l[i(1),i(2),i(3)]"


printer__Gadget_Adapter_String__print_0 =
    Gadget.Adapter.String.print (Gadget.list Gadget.int)


printed__Gadget_Adapter_String__print_0 =
    printer__Gadget_Adapter_String__print_0 [ 1, 2, 3 ]


tools__Gadget_IR__MetadataTools_0 =
    Gadget.IR.makeMetadataTools "MyAdapter"


range__Gadget_IR__MetadataTools_0 : number -> number -> Gadget.IR.Gadget number -> Gadget.IR.Gadget number
range__Gadget_IR__MetadataTools_0 lo hi gadget =
    tools__Gadget_IR__MetadataTools_0.attach
        "range"
        (Gadget.tuple gadget gadget)
        ( lo, hi )
        gadget


rangedIntGadget__Gadget_IR__MetadataTools_0 =
    Gadget.int |> range__Gadget_IR__MetadataTools_0 0 10


metadata__Gadget_IR__MetadataTools_0 =
    rangedIntGadget__Gadget_IR__MetadataTools_0
        |> Gadget.IR.irType
        |> tools__Gadget_IR__MetadataTools_0.extract


irValue__Gadget_IR__MetadataTools_0 =
    tools__Gadget_IR__MetadataTools_0.get
        "range"
        metadata__Gadget_IR__MetadataTools_0


elmValue__Gadget_IR__MetadataTools_0 =
    tools__Gadget_IR__MetadataTools_0.decode
        "range"
        (Gadget.tuple Gadget.int Gadget.int)
        metadata__Gadget_IR__MetadataTools_0


allValues__Gadget_IR__MetadataTools_0 =
    tools__Gadget_IR__MetadataTools_0.debug metadata__Gadget_IR__MetadataTools_0


tools__Gadget_IR__makeMetadataTools_0 =
    Gadget.IR.makeMetadataTools "MyAdapter"
